on:
  push
jobs:
  building:
    name: Download
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repo
        uses: actions/checkout@v2
      -
        run: ls
      -
        name: Build docker image for download step
        run: docker build . --file=docker/download/Dockerfile -t download
      -
        run: docker images
  running:
    needs: building
    runs-on: ubuntu-latest
    steps:
      -
        run: ls $(pwd)
      -
        name: Run docker container for download step
        run: docker run -it download
      -
        run: ls
      
