on:
  push
jobs:
  building:
    name: Eval
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repo
        uses: actions/checkout@v2
      -
        run: ls
      -
        name: Build docker image for eval step
        run: docker build . --file=docker/eval/Dockerfile -t eval
      -
        run: docker images
      -
        run: ls $(pwd)
      -
        name: Run docker container for eval step
        run: docker run -t -v $(pwd)/data:/data eval
      -
        run: ls
