on:
  push
jobs:
  building:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repo
        uses: actions/checkout@v2
      -
        run: ls
      -
        name: Build docker image for prepare step
        run: docker build . --file=docker/prepare/Dockerfile -t prepare
      -
        run: docker images
      -
        run: ls $(pwd)
      -
        name: Run docker container for prepare step
        run: docker run -t -v $(pwd)/data:/data prepare
      -
        run: ls
