on:
  push
jobs:
  idle:
    name: Checkouts
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repo
        uses: actions/checkout@v2
      -
        run: ls
      -
        run: docker build . --file=docker/download/Dockerfile -t download
      -
        run: docker images
      
