
on:
  push
jobs:
  idle:
    name: Train
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repo
        uses: actions/checkout@v2
      -
        run: ls
      -
        name: Build docker image for train step
        run: docker build . --file=docker/train/Dockerfile -t train
      -
        run: docker images
